import assert from "node:assert/strict";
import { mkdtempSync, symlinkSync, unlinkSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { createSnapshot } from "../dist/snapshot.js";
import { validateReport } from "../dist/validate.js";
import { commitAll, git, seedRepository, write } from "./helpers.mjs";

test("working snapshot includes tracked and untracked text while omitting unsafe inputs", () => {
  const root = seedRepository();
  const token = "sk-abcdefghijklmnopqrstuvwxyz123456";
  write(root, "src/app.ts", [
    "export function divide(left: number, right: number): number {",
    `  const OPENAI_API_KEY = \"${token}\";`,
    "DATABASE_PASSWORD=SuperSecretValue123",
    "  if (right === 0) throw new RangeError('right must not be zero');",
    "  return left / right;",
    "}",
    "",
  ].join("\n"));
  write(root, "src/new.ts", "export const first = 1;\nexport const second = 2;\n");
  write(root, "package-lock.json", "{}\n");
  write(root, ".env", `TOKEN=${token}\n`);
  write(root, "generated.js", "// Code generated by fixture. DO NOT EDIT.\nvalue = 1;\n");
  write(root, "image.bin", Buffer.from([0, 1, 2, 3]));
  write(root, "config/secrets.yaml", "password: must-never-appear\n");
  write(root, "credentials.yml", "api_key: must-never-appear-either\n");
  write(root, "config/application.yaml", "password: hunter2secret\napi_key: abcdefghijklmnop\nmode: production\n");

  const snapshot = createSnapshot({ cwd: root });
  assert.deepEqual(createSnapshot({ cwd: root }), snapshot);
  assert.equal(snapshot.repository.root, ".");
  assert.doesNotMatch(JSON.stringify(snapshot), new RegExp(root.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  assert.deepEqual(snapshot.files.map((file) => file.path), ["config/application.yaml", "src/app.ts", "src/new.ts"]);
  const yaml = snapshot.files.find((file) => file.path === "config/application.yaml");
  assert.ok(yaml);
  assert.doesNotMatch(`${yaml.patch}\n${yaml.context.map((block) => block.text).join("\n")}`, /hunter2secret|abcdefghijklmnop/);
  assert.match(yaml.patch, /\[REDACTED\]/);
  const app = snapshot.files.find((file) => file.path === "src/app.ts");
  assert.ok(app);
  assert.ok(app.hunks.some((hunk) => hunk.newRange && hunk.newRange.start <= 2));
  assert.doesNotMatch(app.patch, new RegExp(token));
  assert.doesNotMatch(app.patch, /SuperSecretValue123/);
  assert.doesNotMatch(app.context.map((block) => block.text).join("\n"), /SuperSecretValue123/);
  assert.match(app.patch, /\[REDACTED\]/);
  assert.ok(app.redactions >= 2);
  const added = snapshot.files.find((file) => file.path === "src/new.ts");
  assert.ok(added);
  assert.equal(added.additions, 2);
  assert.equal(added.hunks[0].newRange.end, 2);
  assert.equal(added.context[0].end, 2);
  assert.ok(snapshot.omitted.some((file) => file.path === "package-lock.json" && file.reason === "lockfile"));
  assert.ok(snapshot.omitted.some((file) => file.path === ".env" && file.reason === "sensitive-path"));
  assert.ok(snapshot.omitted.some((file) => file.path === "generated.js" && file.reason === "generated"));
  assert.ok(snapshot.omitted.some((file) => file.path === "image.bin" && file.reason === "binary"));
  assert.ok(snapshot.omitted.some((file) => file.path === "config/secrets.yaml" && file.reason === "sensitive-path"));
  assert.ok(snapshot.omitted.some((file) => file.path === "credentials.yml" && file.reason === "sensitive-path"));
});

test("private key blocks are redacted from both patch and numbered context", () => {
  const root = seedRepository();
  const oldKeyMaterial = "Abcdefghijklmnopqrstuvwxyz0123456789OLD";
  const keyTemplate = (keyMaterial) => [
    "export const key = `-----BEGIN PRIVATE KEY-----",
    keyMaterial,
    "-----END PRIVATE KEY-----`;",
    "",
  ].join("\n");
  write(root, "src/key.ts", keyTemplate(oldKeyMaterial));
  commitAll(root, "private key fixture");
  const keyMaterial = "Zbcdefghijklmnopqrstuvwxyz0123456789NEW";
  write(root, "src/key.ts", keyTemplate(keyMaterial));
  const snapshot = createSnapshot({ cwd: root });
  const keyFile = snapshot.files.find((file) => file.path === "src/key.ts");
  assert.ok(keyFile);
  assert.doesNotMatch(keyFile.patch, new RegExp(keyMaterial));
  assert.doesNotMatch(keyFile.patch, new RegExp(oldKeyMaterial));
  assert.doesNotMatch(keyFile.context.map((block) => block.text).join("\n"), new RegExp(keyMaterial));
  assert.match(keyFile.patch, /\[REDACTED\]/);
});

test("default working snapshot in an unborn repository reflects worktree content", () => {
  const root = seedRepository();
  git(root, ["checkout", "--orphan", "unborn"]);
  git(root, ["rm", "-rf", "."]);
  write(root, "src/state.ts", "export const state = 'indexed';\n");
  git(root, ["add", "src/state.ts"]);
  write(root, "src/state.ts", "export const state = 'worktree';\n");
  const snapshot = createSnapshot({ cwd: root });
  const state = snapshot.files.find((file) => file.path === "src/state.ts");
  assert.equal(state.status, "added");
  assert.match(state.patch, /worktree/);
  assert.doesNotMatch(state.patch, /indexed/);
});

test("working snapshot never follows an untracked symlink outside the repository", { skip: process.platform === "win32" }, () => {
  const root = seedRepository();
  const outside = mkdtempSync(join(tmpdir(), "acr-outside-"));
  const target = write(outside, "private.ts", "export const stolen = 'outside-secret';\n");
  symlinkSync(target, join(root, "src", "linked.ts"));
  const snapshot = createSnapshot({ cwd: root });
  assert.equal(snapshot.files.some((file) => file.path === "src/linked.ts"), false);
  assert.ok(snapshot.omitted.some((file) => file.path === "src/linked.ts" && file.reason === "unreadable"));
  assert.doesNotMatch(JSON.stringify(snapshot), /outside-secret/);
});

test("staged snapshot reads index content and ignores later worktree edits", () => {
  const root = seedRepository();
  write(root, "src/app.ts", "export const state = 'staged';\n");
  git(root, ["add", "src/app.ts"]);
  write(root, "src/app.ts", "export const state = 'unstaged';\n");

  const snapshot = createSnapshot({ cwd: root, mode: "staged" });
  assert.equal(snapshot.files.length, 1);
  assert.match(snapshot.files[0].patch, /staged/);
  assert.doesNotMatch(snapshot.files[0].patch, /unstaged/);
  assert.match(snapshot.files[0].context[0].text, /staged/);
  assert.doesNotMatch(snapshot.files[0].context[0].text, /unstaged/);
});

test("base snapshot uses committed HEAD content rather than dirty worktree content", () => {
  const root = seedRepository();
  write(root, "src/app.ts", "export const state = 'feature';\n");
  commitAll(root, "feature");
  write(root, "src/app.ts", "export const state = 'dirty';\n");

  const snapshot = createSnapshot({ cwd: root, mode: "base", base: "HEAD~1" });
  assert.equal(snapshot.files.length, 1);
  assert.match(snapshot.files[0].patch, /feature/);
  assert.match(snapshot.files[0].context[0].text, /feature/);
  assert.doesNotMatch(snapshot.files[0].context[0].text, /dirty/);
  assert.match(snapshot.repository.base ?? "", /^[a-f0-9]{40,64}$/);
});

test("commit snapshot reviews the requested commit instead of the current worktree", () => {
  const root = seedRepository();
  write(root, "src/app.ts", "export const state = 'first-commit';\n");
  commitAll(root, "first feature change");
  const reviewed = git(root, ["rev-parse", "HEAD"]).trim();
  write(root, "src/app.ts", "export const state = 'later-commit';\n");
  commitAll(root, "later change");
  write(root, "src/app.ts", "export const state = 'dirty-worktree';\n");

  const snapshot = createSnapshot({ cwd: root, mode: "commit", head: reviewed });
  assert.equal(snapshot.repository.mode, "commit");
  assert.equal(snapshot.repository.head, reviewed);
  assert.match(snapshot.files[0].patch, /first-commit/);
  assert.doesNotMatch(snapshot.files[0].patch, /later-commit|dirty-worktree/);
});

test("pull-request snapshot compares explicit revisions independent of checkout", () => {
  const root = seedRepository();
  const base = git(root, ["rev-parse", "HEAD"]).trim();
  git(root, ["checkout", "-b", "feature/pr-review"]);
  write(root, "src/pr.ts", "export const reviewed = true;\n");
  commitAll(root, "pull request change");
  const head = git(root, ["rev-parse", "HEAD"]).trim();
  git(root, ["checkout", "main"]);

  const snapshot = createSnapshot({ cwd: root, mode: "pull-request", base, head });
  assert.equal(snapshot.repository.mode, "pull-request");
  assert.equal(snapshot.repository.head, head);
  assert.deepEqual(snapshot.files.map((file) => file.path), ["src/pr.ts"]);
  assert.match(snapshot.files[0].patch, /reviewed = true/);
});

test("configured ignore paths are excluded before snapshot processing", () => {
  const root = seedRepository();
  write(root, "generated/ignored.ts", "export const generated = true;\n");
  write(root, "src/reviewed.ts", "export const reviewed = true;\n");
  const snapshot = createSnapshot({ cwd: root, ignorePaths: ["generated"] });
  assert.deepEqual(snapshot.files.map((file) => file.path), ["src/reviewed.ts"]);
  assert.equal(snapshot.omitted.some((file) => file.path === "generated/ignored.ts"), false);
});

test("deleted lines are reviewable only on the old side", () => {
  const root = seedRepository();
  unlinkSync(`${root}/src/delete-me.ts`);
  const snapshot = createSnapshot({ cwd: root });
  const deleted = snapshot.files.find((file) => file.path === "src/delete-me.ts");
  assert.equal(deleted.status, "deleted");
  assert.equal(deleted.hunks[0].newRange, null);
  assert.deepEqual(deleted.hunks[0].oldRange, { start: 1, end: 1 });

  const report = {
    schemaVersion: "1.0",
    scope: { kind: "working-tree", base: null, head: null },
    summary: "The deletion removes an exported compatibility symbol.",
    findings: [{
      id: "ACR-001",
      priority: "P1",
      confidence: 0.9,
      category: "correctness",
      file: "src/delete-me.ts",
      startLine: 1,
      endLine: 1,
      title: "Export removal breaks existing imports",
      evidence: "The only changed old-side line deletes the exported obsolete symbol.",
      failureScenario: "Existing consumers importing obsolete fail during module loading after this change.",
    }],
  };
  assert.equal(validateReport(report, snapshot).valid, true);
  report.findings[0].side = "new";
  const invalid = validateReport(report, snapshot);
  assert.ok(invalid.errors.some((issue) => issue.code === "LINE_OUTSIDE_SNAPSHOT"));
});

test("context and global limits are deterministic and reported", () => {
  const root = seedRepository();
  write(root, "src/app.ts", Array.from({ length: 30 }, (_, index) => `export const value${index} = ${index};`).join("\n") + "\n");
  write(root, "src/zzz-another.ts", "export const another = true;\n");
  const snapshot = createSnapshot({
    cwd: root,
    contextLines: 0,
    maxContextLines: 5,
    maxFiles: 1,
  });
  assert.equal(snapshot.files.length, 1);
  assert.equal(snapshot.files[0].context.reduce((count, block) => count + block.end - block.start + 1, 0), 5);
  assert.equal(snapshot.files[0].truncated, true);
  assert.ok(snapshot.omitted.some((file) => file.reason === "file-limit"));
  assert.equal(snapshot.summary.truncated, true);
});
